<?php
/**
 *============================
 * author:Farmer
 * time:2018/8/22 14:15
 * blog:blog.icodef.com
 * function:smtp发信协议
 *============================
 */


namespace HuanL\Protocol;


class SMTP extends Client {

    /**
     * SMTP constructor.
     * @param string $server
     * @param string $user
     * @param string $pwd
     * @param int $port
     * @throws SMTPException
     */
    public function __construct(string $server, string $user, string $pwd, int $port = 25) {
        parent::__construct($server, $port, 1);
        //两秒超时
        $this->timeout(2, 2);
        $read = $this->read(1024);
        if (($code = substr($read, 0, 3)) != '220') {
            //不是smtp服务器,没给我们打招呼,抛出异常
            throw new SMTPException('smtp server returns a reject code', $code);
        }
        $this->login($user, $pwd);
    }

    protected function login($user, $pwd) {
        $input = ['username:' => $user, 'password:' => $pwd];
        //登录用户
        $this->sendCommand('helo ' . $user);
        $read = $this->readCommand('250', 'login error');

        $this->sendCommand('auth login ');
        $read = $this->readCommand('334', 'login error');

        $key = strtolower(base64_decode(substr($read, strpos($read, ' ') + 1)));
        $this->sendCommand(base64_encode($input[$key]));
        $read = $this->readCommand('334', 'login error');

        $key = strtolower(base64_decode(substr($read, strpos($read, ' ') + 1)));
        $this->sendCommand(base64_encode($input[$key]));

        $this->readCommand('235', 'login fail');

    }

    /**
     * 读取命令行
     * @param $code
     * @param string $errmsg
     * @return string
     * @throws SMTPException
     */
    protected function readCommand($code, $errmsg = '') {
        $read = $this->read(1024);
        if (($errcode = substr($read, 0, 3)) != $code) {
            throw new SMTPException($errmsg, $errcode);
        }
        return trim($read);
    }

    /**
     * 发送一条命令
     * @param string $data
     * @return int
     */
    public function sendCommand(string $data): int {
        return parent::send($data . "\r\n"); // TODO: Change the autogenerated stub
    }


}